services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tzhub_db
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: tzhub_db
      DB_USER: user
      DB_PASS: password
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
